<?php
return [
    'Herota' => 'Ebanaya',
    'newKey' => 'new Value',
    'signIn' => 'Sign In',
    'singUP' => 'Sign Up',
    'ok' => 'Ok',
    'add' => 'Add',
    'pay' => 'Pay',
    'copy' => 'Copy',
    'open' => 'Open',
    'next' => 'Next',
    'prev' => 'Prev',
    'save' => 'Save',
    'edit' => 'Edit',
    'login' => 'Login',
    'close' => 'Close',
    'cancel' => 'Cancel',
    'webSave' => 'Save!',
    'delete' => 'Delete',
    'refresh' => 'Refresh',
    'viewMore' => 'View More',
    'usePage' => 'Use page',
    'delAcc' => 'Delete Account',
    'goToBot' => 'Go to Bot',
    'typePrivate' => 'Private',
    'typeBusiness' => 'Business',
    'dashboard' => 'Dashboard',
    'createPage' => 'Create Page',
    'webchatPreview' => 'Preview!',
    'deployToSlack' => 'Deploy to Slack',
    'addApiChannel' => 'Add API channel',
    'addWebChannel' => 'Add web channel',
    'loginWithFb' => 'Login with Facebook',
    'advancedOptions' => 'Advanced Options',
    'saveGreetingMessage' => 'Save Greeting Message',
];